# Site settings
title: Krazov’s writings
email: krazov@interia.pl
description: > # this means to ignore newlines until "baseurl:"
  I share my experience of working with frontend with readers.
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
permalink: /:categories/:title