# Site settings
title: Krazov
email: krazov@interia.pl
description: > # this means to ignore newlines until "baseurl:"
  Strona, na której dzielę się swoimi doświadczeniami zebranymi podczas
  pracy jako frontendowiec.
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
permalink: /:categories/:title